on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Xcode beta
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0-beta"
      - name: Build
        run: swift build
      - name: Test
        run: swift test --enable-swift-testing
